### ISSUE TITLE
Cannot load version property from file

### ISSUE THREAD

**Issue by takecare** [novoda/gradle-build-properties-plugin#11] opened 2017-02-08 15:44 UTC
At the moment you can't load a property named `version` from your properties file.

Example file, `myprops.properties`:

```
name=pirata
version=1.2.3
```

If you attempt to load the `version` property you'll always get `unspecified`. This happens because [PojoMetaMethodSite](http://docs.groovy-lang.org/2.4.3/html/gapi/org/codehaus/groovy/runtime/callsite/PojoMetaMethodSite.html) defines a [version](http://docs.groovy-lang.org/2.4.3/html/gapi/org/codehaus/groovy/runtime/callsite/PojoMetaMethodSite.html#version) field that collides with the `Entry`'s one.

**Comment by mr-archano** [comment] 2017-02-08 15:45
Thanks @takecare for filing this. It's a little bit unfortunate, we'll try to find a workaround.

**Comment by takecare** [comment] 2017-02-08 15:47
👍  can just use any other name as a quick fix though, e.g. `versionValue=1.2.3`

**Comment by stefanhoth** [comment] 2017-02-08 16:43
(In case we need to blacklist "version")
How about a properties validator? Could be useful in general.

**Comment by mr-archano** [comment] 2017-02-10 09:10
@takecare we quickly took a look at this yesterday with @devisnik and we realised the problem is not Groovy, but a bug in the plugin: we first check if there is any project property with the same name, but `project` contains `version` by default (but undefined) therefore the value from the properties file is never read.

We are seriously considering to remove this "feature" because it would be easily scriptable on top of the plugin functionality when needed.

**Comment by tasomaniac** [comment] 2017-02-10 11:01
Hmm,  I have been wondering about that project property look up actually. Users can always do that by using or support. Or if they already have it in project, I don't know why you would use the plugin. I would also vote for removal.

**Comment by mr-archano** [comment] 2017-02-10 13:00
This should be fixed by #12

**Comment by takecare** [comment] 2017-02-10 15:36
could've been checked with a test :trollface:

**Comment by mr-archano** [comment] 2017-02-10 15:57
You mean a failing test? I did check with a test when I realised the problem was `project.version` 💃

**Closed** 2017-02-15 14:12 UTC
Labels: bug
